# Github Action: Recreate Branch From Master
# 
# This github action will recreate an existing 
# branch from the master branch.

name: Recreate Branch From Master

# CUSTOM MESSAGE TO SHOW ON THE WORKFLOW LISTING
run-name: Recreating ${{ github.event.inputs.branch_name }} branch from master branch

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Which branch do you want to recreate?'
        required: true
        type: choice
        options:
        - develop
        - release
        - idev
        - qa

jobs:
  auto-recreate:
    name: Recreate an existing branch from master branch

    # MAX MINUTES BEFORE THIS WORKFLOW TIMESOUT
    timeout-minutes: 15

    # SET TECH STACK
    runs-on: ubuntu-20.04

    # STEPS TO EXECUTE
    steps:
    - uses: actions/checkout@v3
      with:
        ref: master

    # COMMIT ANY MODIFIED FILES TO THE REPO (DONT PUSH UP)
    - name: Delete and recreate new version of the branch
      if: github.event.inputs.branch_name != 'master'
      run: |
        git config --global user.name "${{ secrets.CICD_USER_NAME }}"
        git config --global user.email "${{ secrets.CICD_USER_NAME }}@users.noreply.github.com"
        git push origin --delete ${{ github.event.inputs.branch_name }}
        git checkout master
        git pull
        git branch ${{ github.event.inputs.branch_name }}
        git push --set-upstream origin ${{ github.event.inputs.branch_name }}